KappaCreations/Controllers/ApplicationUserController.cs
using KappaCreations.Database;
using KappaCreations.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace KappaCreations.Controllers
{
    [Authorize(Roles = "User")]
    public class ApplicationUserController : Controller
    {
        private readonly ShopContext _db;

        public ApplicationUserController()
        {
            _db = new ShopContext();
        }

        // GET: ApplicationUser
        public ActionResult Index()
        {
            
            string username = User.Identity.Name;
            
      
            var user = _db.Users.First(u => u.UserName == username);
            

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Birthdate,PhotoUrl,Email,PhoneNumber,UserName")] string id)
        {
            if (ModelState.IsValid)
            {
                string username = User.Identity.Name;
                var user = _db.Users.First(u => u.UserName == username);
                _db.Users.Add(user);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(User);
        }



        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = GetCurrentUser();
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Birthdate,PhotoUrl,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUserManager applicationUser)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(applicationUser).State = EntityState.Modified;
               _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }


        private string GetCurrentUser()
        {
            string username = User.Identity.Name;
            var user = _db.Users.First(u => u.UserName == username);
            string id = user.Id;
            return id;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

KappaCreations/Controllers/ShoppingCartController.cs
using KappaCreations.Database;
using KappaCreations.Models;
using KappaCreations.Models.ViewModels;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KappaCreations.Controllers
{
    public class ShoppingCartController : Controller
    {
        readonly ShopContext _db;


        public ShoppingCartController()
        {
            _db = new ShopContext();
            if (Session != null && Session["cart"] == null)
            {
                List<CartItem> cart = new List<CartItem>();
                Session["cart"] = cart;
            }
        }


        public ShoppingCartController(ShopContext db)
        {
            if (Session != null && Session["cart"] == null)
            {
                List<CartItem> cart = new List<CartItem>();
                Session["cart"] = cart;
            }
            _db = db;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CheckoutForm()
        {
            var name = User.Identity.Name;
            var user = _db.Users.FirstOrDefault(x => x.UserName == name);

            ViewBag.UserId = user.Id;
            return View();
        }



       

        public async Task<ActionResult> Buy(int? id)
        {
            

            if (Session["cart"] == null)
            {
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem
                {
                    Product = await _db.Products
                                       .Where(x => x.Id == id)
                                       .Include(x => x.Category)
                                       .SingleOrDefaultAsync(),
                    Quantity = 1
                });
            Session["cart"] = cart;
            }
            else
            {
                List<CartItem> cart = (List<CartItem>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartItem
                    {
                        Product = await _db.Products
                                           .Where(x => x.Id == id)
                                           .Include(x => x.Category)
                                           .SingleOrDefaultAsync(),
                        Quantity = 1
                    }
                );
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int? id)
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            int index = isExist(id);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }

        public int isExist(int? id)
        {
            List<CartItem> cart = (List<CartItem>)Session["cart"];
            for (int i = 0; i < cart.Count(); i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }

            }

            return -1;
        }




        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal
                //Payer Id will be returned when payment proceeds or click to pay
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist
                    //it is returned by the create function call of the payment class
                    // Creating a payment
                    // baseURL is the url on which paypal sendsback the data.
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority +
                    "/ShoppingCart/PaymentWithPayPal?";
                    //here we are generating guid for storing the paymentID received in session
                    //which will be used in the payment execution
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url
                    //on which payer is redirected for paypal account payment
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    //get links returned from paypal in response to Create function call
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = String.Empty;
                    while (links.MoveNext())
                    {
                        Links link = links.Current;
                        if (link.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = link.href;
                        }
                    }
                    // saving the paymentID in the key guid
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("Failure");
                    }
                }
            }
            catch
            {
                return View("Failure");
            }
            //on successful payment, show success page to user.
            return View();
        }
        private PayPal.Api.Payment payment;
        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution() { payer_id = payerId };
            this.payment = new Payment() { id = paymentId };
            return this.payment.Execute(apiContext, paymentExecution);
        }
        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
            //create itemlist and add item objects to it
            var itemList = new ItemList() { items = new List<Item>() };

            List<CartItem> listCarts = (List<CartItem>)Session["cart"];

            foreach (var cart in listCarts)
            {
                itemList.items.Add(new Item()
                {
                    name = cart.Product.Category.Title,
                    currency = "EUR",
                    price = cart.Product.Category.Price.ToString(),
                    quantity = cart.Quantity.ToString(),
                    sku = "sku"
                });
            }
            //Adding Item Details like name, currency, price etc

            var payer = new Payer() { payment_method = "paypal" };
            // Configure Redirect Urls here with RedirectUrls object
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };
            // Adding Tax, shipping and Subtotal details
            var details = new Details()
            {
                tax = "1",
                shipping = "2",
                subtotal = listCarts.Sum(x => x.Quantity * x.Product.Category.Price).ToString()
            };
            //Final amount with details
            var amount = new Amount()
            {
                currency = "EUR",
                total = (Convert.ToDouble(details.tax) + Convert.ToDouble(details.shipping) + Convert.ToDouble(details.subtotal)).ToString(), // Total must be equal to sum of tax, shipping and subtotal.
                details = details
            };
            var transactionList = new List<Transaction>();
            // Adding description about the transaction
            transactionList.Add(new Transaction()
            {
                description = "Transaction description",
                invoice_number = Convert.ToString((new Random()).Next(100000)), //Generate an Invoice No
                amount = amount,
                item_list = itemList
            });
            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };
            // Create a payment using a APIContext
            return this.payment.Create(apiContext);
        }





    }
}

KappaCreations/Views/Shared/ClientComponent/_Footer.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-12 width-50 width-set-50">
                <div class="footer-details">
                    <h4>quick links</h4>
                    <ul class="list-unstyled footer-links">
                        <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Create", "Create", "Home")</li>
                        <li>@Html.ActionLink("Gallery", "Index", "Gallery")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-sm-3 col-xs-12 width-set-50">
                <div class="footer-details">
                    <h4>working hours</h4>
                    <ul class="list-unstyled time-schedule-list">
                        <li><span>Mon : 09:00 - 15:00</span></li>
                        <li><span>tue : 09:00 - 21:00</span></li>
                        <li><span>wed : 09:00 - 15:00</span></li>
                        <li><span>thu : 09:00 - 21:00</span></li>
                        <li><span>fri : 09:00 - 21:00</span></li>
                        <li><span>sat : 09:00 - 15:00</span></li>

                        <li class="change-col"><span>Sun : Closed</span></li>
                    </ul>
                </div>

            </div>

            <div class="col-md-3 col-sm-3 col-xs-12 insta-block width-set-50">
                <div class="footer-details">
                    <h4>contact us</h4>
                    <ul class="list-unstyled footer-contact-list">
                        <li>
                            <i class="fa fa-location-arrow fa-lg"></i>
                            <p>Address: 10, Ardittou St., Athens, Greece</p>
                        </li>
                        <li>
                            <i class="fa fa-phone fa-lg"></i>
                            <p> Tel.: +30 210 9211111</p>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-lg"></i>
                            <p><a href="mailto:kappashop2022@gmail.com">kappashop2022@gmail.com</a></p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="copyright">
            <!--Do not remove Backlink from footer of the template. To remove it you can purchase the Backlink !-->
            &copy; 2017 All right reserved. Designed by <a href="http://www.themevault.net/" target="_blank">ThemeVault.</a>
        </div>
        <!--back to top--->
        <a style="display: none;" href="javascript:void(0);" class="scrollTop back-to-top" id="back-to-top">
            <span><i aria-hidden="true" class="fa fa-angle-up fa-lg"></i></span>
            <span>Top</span>
        </a>
    </div>
</footer>

KappaCreations/Views/Shared/ClientComponent/_Header.cshtml
@using KappaCreations.Models

@{
    ViewBag.Title = "Log in";
}
@{
    string userName = User.Identity.Name;
    bool isAdmin = User.IsInRole("Admin");
}
<!---header top---->
<div class="top-header">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-10 col-xs-12">
                <div class="info-block">
                    <ul>
                        <li><p><i class="fa fa-location-arrow fa-lg"></i>Address: 10, Ardittou St., Athens</p></li>
                        <li><i class="fa fa-phone fa-lg"></i>  Tel.: +30 210 9211111 </li>
                        <li><i class="fa fa-envelope"></i> <a href="mailto:kappashop2022@gmail.com"> kappashop2022@gmail.com</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-6">
                <div class="login-block">
                    @if (string.IsNullOrWhiteSpace(userName))
                    {
                        <a id="mmm" href="../Account/Login">
                            <img src="~/probeautyfly/images/icons/login.png" alt="login"><span>Login</span>
                        </a>
                    }
                    else
                    {
                        if (isAdmin)
                        {
                            <p style="margin-top:4px">@Html.ActionLink("Dashboard", "Index", "Admin")</p>
                        }
                        else
                        {
                            <p style="margin-top:4px">@Html.ActionLink("Welcome, " + @userName, "Index", "ApplicationUser")</p>
                        }
                    }
                </div>
            </div>
            <div  style="margin-top:4px" class="col-md-2 col-sm-2 col-xs-6">
                <i  class="fa fa-shopping-cart">@Html.ActionLink("Shopping Cart", "Index", "ShoppingCart")</i>
            </div>
        </div>
    </div>
</div>
<!--header--->

KappaCreations/Views/Shared/ClientComponent/_NavigationBar.cshtml
<header>
    <nav class="navbar navbar-default">
        <div class="container">

            <div class="row">
                @**@
                <div class="col-md-2 col-sm-2 col-xs-12">
                    <div id="logo"><a href=@Url.Action("Index","Home")><img src="~/probeautyfly/images/Kappa logo Black.jpg" alt="logo"></a></div>
                </div>
                <div class="col-md-8 col-sm-10 col-xs-12 hidden-xs">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "link-effect" })</li>
                            <li>@Html.ActionLink("About", "About", "Home", null, new { @class = "link-effect" })</li>
                            <li>
                                @Html.ActionLink("Create", "Create", "Home", null, new { @class = "link-effect" })
                                <div class="sub-menu-dropdown">
                                    <ul class="test-nav-list">
                                        <li>@Html.ActionLink("Ashtrays", "Create", "Home", null, new { @class = "link-effect", @id = "cat-1" })</li>
                                        <li>@Html.ActionLink("Bags", "Create", "Home", null, new { @class = "link-effect", @id = "cat-2" })</li>
                                        <li>@Html.ActionLink("Bed-Sheets", "Create", "Home", null, new { @class = "link-effect", @id = "cat-3" })</li>
                                        <li>@Html.ActionLink("Canvas", "Create", "Home", null, new { @class = "link-effect", @id = "cat-4" })</li>
                                        <li>@Html.ActionLink("Door-Mats", "Create", "Home", null, new { @class = "link-effect", @id = "cat-5" })</li>
                                        <li>@Html.ActionLink("Hoodies", "Create", "Home", null, new { @class = "link-effect", @id = "cat-6" })</li>
                                        <li>@Html.ActionLink("Magnets", "Create", "Home", null, new { @class = "link-effect", @id = "cat-7" })</li>
                                        <li>@Html.ActionLink("Mousepads", "Create", "Home", null, new { @class = "link-effect", @id = "cat-8" })</li>
                                        <li>@Html.ActionLink("Mugs", "Create", "Home", null, new { @class = "link-effect", @id = "cat-9" })</li>
                                        <li>@Html.ActionLink("Phone-Cases", "Create", "Home", null, new { @class = "link-effect", @id = "cat-10" })</li>
                                        <li>@Html.ActionLink("Pillows", "Create", "Home", null, new { @class = "link-effect", @id = "cat-11" })</li>
                                        <li>@Html.ActionLink("Plates", "Create", "Home", null, new { @class = "link-effect", @id = "cat-12" })</li>
                                        <li>@Html.ActionLink("T-Shirts", "Create", "Home", null, new { @class = "link-effect", @id = "cat-13" })</li>
                                        <li>@Html.ActionLink("Thermos-Bottles", "Create", "Home", null, new { @class = "link-effect", @id = "cat-14" })</li>
                                        <li>@Html.ActionLink("Tissues", "Create", "Home", null, new { @class = "link-effect", @id = "cat-15" })</li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                @Html.ActionLink("Gallery", "Index", "Gallery", null, new { @class = "link-effect" })
                                <div class="sub-menu-dropdown">
                                    <ul>
                                        <li>@Html.ActionLink("Ashtrays", "Index", "Gallery", new { categoryId = 1 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Bags", "Index", "Gallery", new { categoryId = 2 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Bed-Sheets", "Index", "Gallery", new { categoryId = 3 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Canvas", "Index", "Gallery", new { categoryId = 4 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Door-Mats", "Index", "Gallery", new { categoryId = 5 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Hoodies", "Index", "Gallery", new { categoryId = 6 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Magnets", "Index", "Gallery", new { categoryId = 7 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Mousepads", "Index", "Gallery", new { categoryId = 8 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Mugs", "Index", "Gallery", new { categoryId = 9 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Phone-Cases", "Index", "Gallery", new { categoryId = 10 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Pillows", "Index", "Gallery", new { categoryId = 11 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Plates", "Index", "Gallery", new { categoryId = 12 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("T-Shirts", "Index", "Gallery", new { categoryId = 13 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Thermos-Bottles", "Index", "Gallery", new { categoryId = 14 }, new { @class = "link-effect" })</li>
                                        <li>@Html.ActionLink("Tissues", "Index", "Gallery", new { categoryId = 15 }, new { @class = "link-effect" })</li>
                                    </ul>
                                </div>


                            <li>@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "link-effect" })</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <button id="showLeft" class="c-hamburger c-hamburger--htla">
            <span>toggle menu</span>
        </button>
    </nav>

    <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
        <div id="logo" class="text-center"><a href=@Url.Action("Index","Home")><img src="~/probeautyfly/images/Kappa logo Black.jpg" alt="logo"></a></div>

        <ul class="list-unstyled">
            <li class="active"> @Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>


            <li class="ui fluid accordion">
                <div class="title">
                    @Html.ActionLink("Create", "Create", "Home")
                    <i class="dropdown icon"></i>
                </div>
                <div class="content">
                    <ul class="list-unstyled test-nav-list">
                        <li>@Html.ActionLink("Ashtrays", "Create", "Home")</li>
                        <li>@Html.ActionLink("Bags", "Create", "Home")</li>
                        <li>@Html.ActionLink("Bed-Sheets", "Create", "Home")</li>
                        <li>@Html.ActionLink("Canvas", "Create", "Home")</li>
                        <li>@Html.ActionLink("Door-Mats", "Create", "Home")</li>
                        <li>@Html.ActionLink("Hoodies", "Create", "Home")</li>
                        <li>@Html.ActionLink("Magnets", "Create", "Home")</li>
                        <li>@Html.ActionLink("Mousepads", "Create", "Home")</li>
                        <li>@Html.ActionLink("Mugs", "Create", "Home")</li>
                        <li>@Html.ActionLink("Phone-Cases", "Create", "Home")</li>
                        <li>@Html.ActionLink("Pillows", "Create", "Home")</li>
                        <li>@Html.ActionLink("Plates", "Create", "Home")</li>
                        <li>@Html.ActionLink("T-Shirts", "Create", "Home")</li>
                        <li>@Html.ActionLink("Thermos-Bottles", "Create", "Home")</li>
                        <li>@Html.ActionLink("Tissues", "Create", "Home")</li>
                    </ul>

                </div>
                <!--Start Add Text area-->
            </li>



            <li class="ui fluid accordion">
                <div class="title">
                    @Html.ActionLink("Gallery", "Index", "Gallery")
                    <i class="dropdown icon"></i>
                </div>
                <div class="content">
                    <ul class="list-unstyled">
                        <li>@Html.ActionLink("Ashtrays", "Index", "Gallery", new { categoryId = 1 },new{ order = 4 })</li>
                        <li>@Html.ActionLink("Bags", "Index", "Gallery", new { categoryId = 2 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Bed Sheets", "Index", "Gallery", new { categoryId = 3 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Canvas", "Index", "Gallery", new { categoryId = 4 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Door Mats", "Index", "Gallery", new { categoryId = 5 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Hoodies", "Index", "Gallery", new { categoryId = 6 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Magnets", "Index", "Gallery", new { categoryId = 7 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Mousepads", "Index", "Gallery", new { categoryId = 8 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Mugs", "Index", "Gallery", new { categoryId = 9 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Phone Cases", "Index", "Gallery", new { categoryId = 10 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Pillows", "Index", "Gallery", new { categoryId = 11 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Plates", "Index", "Gallery", new { categoryId = 12 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("T-Shirts", "Index", "Gallery", new { categoryId = 13}, new { order = 4 })</li>
                        <li>@Html.ActionLink("Thermos Bottles", "Index", "Gallery", new { categoryId = 14 }, new { order = 4 })</li>
                        <li>@Html.ActionLink("Tissues", "Index", "Gallery", new { categoryId = 15 }, new { order = 4 })</li>
                    </ul>

                </div>
                <!--Start Add Text area-->
            </li>


            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
        </ul>

        <div id="search" class="input-group offspace-30">
            <input type="text" name="search" value="" placeholder="Search" class="form-control search-box placeholder-fix">
            <span class="input-group-btn">
                <button type="button" class="btn search-button"><i class="fa fa-search fa-lg"></i></button>
            </span>
        </div>
        <div class="cp-menu-footer-social-icon offspace-30">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </div>
    </nav>

    <div class="clearfix"></div>
</header>
<!--end-->
<!--end-->
<script src="~/probeautyfly/js/classie.js" type="text/javascript"></script>
<script>
    var menuLeft = document.getElementById('cbp-spmenu-s1'),
        showLeft = document.getElementById('showLeft'),
        body = document.body;

    showLeft.onclick = function () {
        classie.toggle(this, 'active');
        classie.toggle(menuLeft, 'cbp-spmenu-open');
        disableOther('showLeft');
    };

    function disableOther(button) {
        if (button !== 'showLeft') {
            classie.toggle(showLeft, 'disabled');
        }

    }</script>